### ISSUE TITLE
Proje raporunuz yüklenmemiş

### ISSUE THREAD

**Issue by fstasel** [CankayaUniversity/ceng-407-408-2019-2020-Implementation-of-an-Audio-Visual-Emotional-Recognition-System#6]
Proje raporunuz repoya yüklenmemiş. Acilen yüklemeniz gerekli.

**Comment by fstasel** [comment]
master branchinde olmadığı için görünmüyor sanırım. mastera da eklerseniz iyi olur.

**Comment by aydnssman** [comment]
Hocam proje raporumuzu master branchine attık. tekrardan kontrol eder misniz?

**Comment by fstasel** [comment]
ok.
